### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by ndmitchell** [haskell-hvr/hslogger#55]
Would it be possible to add hslogger to Stackage? We'd like to add ghcide to Stackage, which relies on hslogger, and having it already there would make that much simpler.

**Comment by bubba** [comment]
Looks like this is dependent on network-bsd?

**Comment by ndmitchell** [comment]
https://github.com/haskell/network-bsd/issues/6 seems to be the ticket to fix that.

**Comment by bubba** [comment]
@ndmitchell following the trail of breadcrumbs :)

**Comment by hvr** [comment]
Well, I just resolved the blocker; but as far as

> Would it be possible to add hslogger to Stackage?

is concerned, I'll just quote https://github.com/haskell-hvr/.github/edit/master/CONTRIBUTING.md :

> ## FAQ
>
> - **Can you add your packages to Stackage?** No can do; [I have been banned from Stackage](https://github.com/fpco/stackage/issues/4472) but if you haven't been blocked yet, you can try to [file an issue](https://github.com/fpco/stackage/issues/new).

**Comment by ndmitchell** [comment]
@bubba - do you want to do the honours? Since I imagine (if you are after putting lsp-test there) you'll want to do all of haskell-lsp, lsp-test, hslogger, network-bsd in one go? If you'd rather not, I'll do so.

**Comment by bubba** [comment]
@ndmitchell sure, working on it on this PR https://github.com/commercialhaskell/stackage/pull/4996#issuecomment-558259997

**Comment by ysangkok** [comment]
I think this can be closed, since it is already in Stackage: https://github.com/commercialhaskell/stackage/blob/c3e81248a2b943dd92357297cfa47f04b8d6a327/build-constraints.yaml#L4945
